### ISSUE TITLE
Implement camping values on hero detail page

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/ui#11]
We have the data for `camping` (both the conversation type and what each other conversation affects the hero.

Not sure if we should list each of the conversations values. Any suggestions?

**Comment by willhausman** [comment]
I think you might be better off just linking to #12 with pre-filled criteria for selecting this hero's conversation value. That sounds much simpler and cleaner than listing a bunch of text to a view that is already pretty hefty with data.

**Comment by RaphaelDDL** [comment]
Sound good. 

Do we at least show the camping options the hero has? I guess not since #12 would end up having them. I thought of the options and what they talk in each, like Yufine "cute cheer" says something like "im cute, look at me, that's enough" or something like that.

I feel it's a cool lore option, though we don't have this data atm :(

**Comment by willhausman** [comment]
I agree, putting the actual options the character has on the page would be great. For Lore especially.  It makes the character data feel more complete, imo.

**Comment by RaphaelDDL** [comment]
Adding as low since we don't have the camping phrases yet.

**Comment by RaphaelDDL** [comment]
Added the camping options a while ago. I got some camping phrases but I need to re-visit all heroes see if the order is correct before adding.

**Comment by RaphaelDDL** [comment]
V2 brings all data sorted and correct.
