### ISSUE TITLE
Community Recommendations

### ISSUE THREAD

**Issue by willhausman** [EpicSevenDB/ui#13]
This would be a large undertaking, but is potentially interesting.  I think it would be neat to allow users to vote on which artifacts and heroes work well together. Voting so it can change over time without explicit maintenance to the db project.

This information already exists in one form or another on Reddit, but could be automatically maintained in an easier-to-consume fashion than a google doc.

This would require:
Third Party Login to the application (Reddit, Google, Microsoft, Facebook, wherever we want to support)
Unique Tokens across logins used to determine where a user has voted.
Baseline recommendations

Thoughts?

**Comment by RaphaelDDL** [comment]
Unfortunately I want to steer away from both opinionated data as well as user-interaction (login, auth, etc).

Main goal of the DB is to present easy-to-browse factional data, in the same fashion as alchemistcodedb.com (which is my main inspiration). That's the reason there's no comment section (easy to add with disquis), no tier list, no suggestion of what artifact or equip sets to use.


Examples of what I aim:
- https://www.alchemistcodedb.com/unit/achad 
- https://summonerswar.fandom.com/wiki/Chimera_(Water)_-_Taor (only the 'monster' tab, without comments)
