### ISSUE TITLE
Team Builder tool

### ISSUE THREAD

**Issue by willhausman** [EpicSevenDB/ui#14]
I think it would be neat to create a page that allows you compose a Team with equipped artifacts, Guardians, skill upgrades, and awakenings.  Selecting that information would provide a preview of composite buff/debuff chances and some relative indicator of frequency.

The tool would be even better if your selections could be stored with a unique hash in the url, so you can save and share the team with others.

**Comment by RaphaelDDL** [comment]
stocky37 created one using the DB's API: 
- https://old.reddit.com/r/EpicSeven/comments/atb6wf/another_equipment_preview_tool/
- https://stocky37.github.io/epicseven-tools/
- https://github.com/stocky37/epicseven-tools

He's also helping on the db with the multipliers and other stuff. So I'll just point his creation on the tools section (I'm adding a list of everyone who used the API). 

Maybe later we could work together and incorporate into the db (though he made in react so we would need to port it).

**Comment by willhausman** [comment]
Sounds covered.
