### ISSUE TITLE
Create component for Item tooltip

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/ui#15]
Awakening, Skill ups, etc, all require items. We need some way of presenting it better, currently name and quantity, as `Gold x15000, Molagora x1`.

Create a list component (and list item) which receives an array as props and present a list of items. It will also have a tooltip component where on either hover or click, open said tooltip with the item name, type, description (maybe) and acquirable locations (dynamic height since some items have multiple locations).

Small wire of the idea:

![image](https://user-images.githubusercontent.com/1087109/53582560-8375a280-3b5e-11e9-86d8-a6517496d205.png)

where the list item component would look like the in-game Inventory->Other
![image](https://user-images.githubusercontent.com/1087109/56690156-2b1cd600-66b3-11e9-9db5-53fe5cc6b192.png)

And the click/hover would be like the game's tooltip, with extra locations. OR a link to the page created by #8 for locations so doesn't bloat too much.
![image](https://user-images.githubusercontent.com/1087109/53583923-4eb71a80-3b61-11e9-92fb-2697d8978188.png)

**Comment by RaphaelDDL** [comment]
updated in-game menu image with better quality;

component work started

**Comment by RaphaelDDL** [comment]
Released on 0.8.0

Need to update this repo to link the commit :D

**Comment by RaphaelDDL** [comment]
How it looks:

![image](https://user-images.githubusercontent.com/1087109/57099618-3d21f880-6cf3-11e9-87b4-842c37d2e187.png)

<img width="708" alt="2" src="https://user-images.githubusercontent.com/1087109/57099665-59be3080-6cf3-11e9-9844-7da84ff3645d.png">

![image](https://user-images.githubusercontent.com/1087109/57099626-44490680-6cf3-11e9-8ed9-03b1ed63b5ce.png)

**Comment by willhausman** [comment]
That looks awesome! Is it on click or hover? I'm specifically wondering how it behaves on mobile.

**Comment by RaphaelDDL** [comment]
@willhausman It's on both click and tap. Works on mobile too, same way as desktop :) The only thing is that popover will be a smaller (but scrolling inside works too).

I'm using `v-tooltip` vue plugin

**Comment by RaphaelDDL** [comment]
Repo updated to 0.8.0 @ 4499c11e49dc9dba94db4b03a5fc8da94b9753fd
