### ISSUE TITLE
[Suggestion] Implement a filter for memory imprint

### ISSUE THREAD

**Issue by ybouzekri** [EpicSevenDB/ui#21]
Hello,
Let me start by saying thanks for your work on the project.
I would like if possible an option where we can filter heroes by their memory imprint.
like heroes that have an Atk% imprint, or heroes that increase Eff%.
Would be much appreciated.

Thanks

**Comment by RaphaelDDL** [comment]
Hi, 
thank you for your time writing a suggestion. Yup, this is doable. I'll add this to the roadmap :)

**Comment by RaphaelDDL** [comment]
We implemented an easier way to present the memory imprint data on https://github.com/EpicSevenDB/gamedatabase/commit/e21e4b9e369ff7c2ed77ba7089435e6253209860 so now should be easier to create the filter by memory imprint type :D

**Comment by RaphaelDDL** [comment]
Hi @ybouzekri 

 Memory Imprint filters implemented in 10b26dd4f0c651b9f0dd3163adbc5d8e62cd5448 + https://github.com/EpicSevenDB/gamedatabase/commit/48442c1561e3a016ebc592ae849cc2eba0be8fa9 and is Live! 

https://epicsevendb.com/heroes
