### ISSUE TITLE
Add heroes expressions

### ISSUE THREAD

**Issue by Leo22117311** [EpicSevenDB/ui#22]
This is completely unnecessary, but if u guys have time or simply want to make the app complete then go ahead. But i want to see all of the expressions tho. This is a suggestion.

**Comment by RaphaelDDL** [comment]
Still not able to mine expressions, we got just a few ones (Lots and few NPCs). Marking as low until we manage to mine those :'(

**Comment by RaphaelDDL** [comment]
There's now e7herder.com for viewing the models
