### ISSUE TITLE
Destina bug

### ISSUE THREAD

**Issue by BenRiska** [EpicSevenDB/ui#37]
nvm lol

**Comment by RaphaelDDL** [comment]
> Destina gets marked as a unit who uses duel attacks on the filter algorythm

Actually, I'm not sure why her skill 1 is flagged as common 33 (aka dual attack). Nor her skills nor her EE give her that. Is the opposite, her S1 souburn says does not proc a dual attack.

Any idea @Dimbreath ?

**Comment by Dimbreath** [comment]
I gave it a look and they have it listed on her soul burn skill with the tag 33 (Dual Attack.) as for why... I have no clue.

**Comment by RaphaelDDL** [comment]
That's odd.. Well, nothing we can do since we pull directly from game xD

![image](https://user-images.githubusercontent.com/1087109/88699482-c8985e00-d0dd-11ea-9a5b-8e8416034875.png)
(change japanese for korean/SG)

**Comment by RaphaelDDL** [comment]
Well, marking as won't fix since if I manually remove, next game update it'll show up again. 🤷
