### ISSUE TITLE
Chinese Traditional webpage bug

### ISSUE THREAD

**Issue by zx900930** [EpicSevenDB/ui#38]
The lang should be zht not tw, lang=tw returns no data.
now its not translated.
example: 
https://epicsevendb.com/tw/hero/alencia
https://api.epicsevendb.com/hero/alencia?lang=zht
probably can be fixed by add 'tw' to the requestedLanguage list
https://github.com/EpicSevenDB/api/pull/11

**Comment by RaphaelDDL** [comment]
Thanks for catching it.

I added to the switch below the lang check (to change tw to zht) but didn't add to the list of acceptable langs

**Comment by RaphaelDDL** [comment]
Ok, API deployed.

https://epicsevendb.com/tw/hero/alencia

Thank you 👍
