### ISSUE TITLE
Hero kikirat-v2 has no "values" in camping information

### ISSUE THREAD

**Issue by meowyih** [EpicSevenDB/ui#42]
Hero kikirat-v2 has no "values" information in camping section. This issue can be reproduced by querying https://api.epicsevendb.com/hero/kikirat-v2 Here is Kikirat v2's camping section
"camping": {
        "topics": [
          "Belief",
          "Unique Comment"
        ]
      }

**Comment by RaphaelDDL** [comment]
👍 
moved to https://github.com/EpicSevenDB/gamedatabase/issues/255
